number = float(input("please enter a four digit number:\n"))
three_digitnumber = int(number // 10)
tow_digitnumber = int(number // 100)
one_digitnumber = int(number // 1000)
print(three_digitnumber, "\n", tow_digitnumber, "\n", one_digitnumber,)
