w = "Hello"
print(w.upper())
print(w.lower())
print(w.isupper())
print(w.islower())
print(w.capitalize())
print(w.title())
print(w.startswith())
print(w.endswith())
print(w.count())
print(w.strip())
dir('')
w.rstrip()
w.lstrip()
