name1 = input("enter name:\n")
name2 = input("enter name:\n")
name3 = input("enter name:\n")
name4 = input("enter name:\n")
name5 = input("enter name:\n")
name6 = input("enter name:\n")
name7 = input("enter name:\n")
name8 = input("enter name:\n")
name9 = input("enter name:\n")
name10= input("enter name:\n")
character = input("enter youre character:\n")
name1_c = name1.count(character)
name2_c = name2.count(character)
name3_c = name3.count(character)
name4_c = name4.count(character)
name5_c = name5.count(character)
name6_c = name6.count(character)
name7_c = name7.count(character)
name8_c = name8.count(character)
name9_c = name9.count(character)
name10_c= name10.count(character)
sum = name1_c + name2_c + name3_c + name4_c + name5_c + name6_c + name7_c + name8_c + name9_c + name10_c 
print("in", name1.title(), "is", name1_c, character)
print("in", name2.title(), "is", name2_c, character)
print("in", name3.title(), "is", name3_c, character)
print("in", name4.title(), "is", name4_c, character)
print("in", name5.title(), "is", name5_c, character)
print("in", name6.title(), "is", name6_c, character)
print("in", name7.title(), "is", name7_c, character)
print("in", name8.title(), "is", name8_c, character)
print("in", name9.title(), "is", name9_c, character)
print("in", name10.title(),"is", name10_c,character)
print("at all", character, "reapiting by", sum)